### ISSUE TITLE
Doesn't work in IE8 or IE9

### ISSUE THREAD

**Issue by AaronLayton** [andreruffert/rangeslider.js#183]
I did a Bower install and I have tried the latest version 2.0.2 and an older one 1.3.3 and both times this doesn't work

It initialises but you can't drag anything around - checking your main site and the same thing happens

**Comment by andreruffert** [comment]
Hi @AaronLayton!

Do you have any errors in the console?

**Comment by AaronLayton** [comment]
@andreruffert no nothing is shown in the console.

I have attached an image showing your site not working correctly, note the green bar... 
![2015-10-30_09h16_54](https://cloud.githubusercontent.com/assets/694964/10842105/fc498bdc-7ee6-11e5-8e59-7cfeb615a3e9.png)

I can click the `.rangeslider rangeslider--horizontal` a few times and bet the `.rangeslider__fill` to update, but the `.rangeslider__handle` does not move.

Note I am actually using IE11 in IE9 emulation mode

**Comment by andreruffert** [comment]
Hi @AaronLayton I fixed it on [andreruffert.github.io/rangeslider.js](http://andreruffert.github.io/rangeslider.js/).
The problem was that I load the CSS non-blocking via JS. rangeslider.js needs at least `.rangeslider__handle { width: 42px; }` for calculation. Form more details see b3a2871.

Do you load your CSS non-blocking?

**Comment by AaronLayton** [comment]
@andreruffert I will give it another try tomorrow, I believe I just installed this through bower though and let wiredep add in the css for me
