### ISSUE TITLE
ToolTip is not displayed

### ISSUE THREAD

**Issue by octaviodiaz** [andreruffert/rangeslider.js#204]
When I set the tooltip especificaly from bootstrap , it does not show up :/.

**Comment by andreruffert** [comment]
If u have a example (CodePen, jsfiddle etc.) what exactly is not working I guess we can figure it out why it does not show up 🤖

**Comment by octaviodiaz** [comment]
yes , sorry :P . I just uncomment the initialization of your beautiful slider and then it does not work.

Here is the code http://codepen.io/anon/pen/XXaeda

**Comment by andreruffert** [comment]
K I see :) The `<input type="range">` element get's hidden after the rangeslider.js initialization that's why the tooltip doesn't show up any more.
Simple solution would be to set the tooltip attributes (`data-toggle="tooltip"` etc.) to the generated `.rangeslider` element. You can do this for example in the `onInit()` hook.

http://codepen.io/anon/pen/JGyrOa?editors=001

**Comment by octaviodiaz** [comment]
Thanks !!!
